### ISSUE TITLE
Office League - PWA - Cache requests to GraphQL

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-office-league#99]
Depends on #88

**Comment by aro** [comment]
It does not work in admin mode, I get always redirected to the offline page no matter what:

http://localhost:8080/admin/portal/preview/draft/office-league/app

**Comment by alansemenov** [comment]
@aro Can you try clearing the cache? Or open a window in Incognito mode. I can't reproduce it in either admin or live mode. I did get one issue though after Pavel's commit, with .js libs not being fetched from cache - fixed that now.

**Comment by aro** [comment]
@alansemenov I keep being randomly redirected to the offline page, not only on admin mode. I tried with incognito mode and in firefox also. It happens by navigating through players, leagues, maybe going back to the league.
It should not be that whenever a request fails we are sent to the offline page, then there would be no offline functionality at all.

I have enabled the offline game saving again (IndexedDB). Try this while being online:
- Log in
- Go to a league page and click on Play
- Select 2 players
- Go offline
- Click play
- Score goals
- It should work, write the game in indexeddb and not send you back to the offline page
- Finish the game
- Go online again

**Comment by aro** [comment]
@alansemenov  I think I found the problem. I have some bad data that makes that something fails in a callback from graphQLService.post(). Since it's in the post call it probably is handled as a network error. It was in PlayerProfileComponent.handlePlayerLeagueQueryResponse .
After avoiding the error in the callback I don't get sent to the offline page anymore. Sorry, my mistake.
But I'm still unsure if we should go to the offline page every time a request fails.

**Comment by GlennRicaud** [comment]
Maybe a check to navigator.onLine
